# Generated by Django 2.1.4 on 2018-12-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_time_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='day',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
